(deftheme eiio-theme
  "Created 2017-08-14.")
(custom-theme-set-faces
 'eiio-theme
 '(default ((t (:family "Source Code Pro" :foundry "nil" :width normal :height 180 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#ABB2BF" :background "#282C34" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#CDD3D3" :background "#AEB9F5"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#C792EA"))))
 '(minibuffer-prompt ((t (:foreground "#AAAAAA"))))
 '(highlight ((t (:background "#3E4451"))))
 '(region ((t (:background "#3E4451"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#121417"))))
 '(trailing-whitespace ((t (:background "#FF516D"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#56B6C2"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#546D7A" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#5C6370"))))
 '(font-lock-constant-face ((t (:foreground "#56B6C2"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#61AFEF"))))
 '(font-lock-keyword-face ((t (:foreground "#C678DD"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#FFCB6B"))))
 '(font-lock-preprocessor-face ((t (:foreground "#828997"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#546D7A"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#FFC400"))))
 '(font-lock-string-face ((t (:foreground "#98C379"))))
 '(font-lock-type-face ((t (:foreground "#E5C07B"))))
 '(font-lock-variable-name-face ((t (:foreground "#E06C75"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#5C6370"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#61AFEF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#61AFEF"))))
 '(fringe ((t (:foreground "#CDD3D3" :background "#282C34"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#FFCB6B" :background "#2B3B40"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#AAAAAA" :background "#0F1011"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#FFCB6B"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#CDD3D3" :background "#3E4451"))))
 '(isearch ((t (:weight bold :foreground "#282C34" :background "#C678DD"))))
 '(isearch-fail ((t (:foreground "#BE5046"))))
 '(lazy-highlight ((t (:weight bold :underline (:color "#C678DD" :style line) :foreground "#C678DD" :background "#121417"))))
 '(match ((t (:weight bold :foreground "#C2E982" :background "#2B3B40"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'eiio-theme)
