(require-package 'flycheck)
;;(require-package 'flycheck-highlighting)
;;(require-package 'flycheck-indication)
(require-package 'flycheck-tip)
(global-flycheck-mode)
(require-package 'flycheck-color-mode-line)
(setq flycheck-highlighting-mode 'lines)
(setq flycheck-indication-mode 'right-fringe)
(require 'flycheck-color-mode-line)

(eval-after-load "flycheck"
    '(add-hook 'flycheck-mode-hook 'flycheck-color-mode-line-mode))
;;(flymake-cursor-mode t)
(add-hook 'lua-mode-hook 'flymake-lua-load)
;;(add-hook 'find-file-hook 'flymake-find-file-hook)
(provide 'init-flycheck)
