(require-package 'flycheck)
(require-package 'flycheck-status-emoji)
(require-package 'flycheck-tip)
(global-flycheck-mode)
(require-package 'flycheck-color-mode-line)
(setq flycheck-highlighting-mode 'sexps)
;;(setq flycheck-indication-mode 'left-fringe)

(require 'flycheck-color-mode-line)

(eval-after-load "flycheck"
    '(add-hook 'flycheck-mode-hook 'flycheck-color-mode-line-mode))
;;(flymake-cursor-mode t)
(add-hook 'lua-mode-hook 'flymake-lua-load)
;;(add-hook 'find-file-hook 'flymake-find-file-hook)
;;(set-fontset-font t nil "Symbola")
(setq flycheck-warning nil)
(setq flycheck-error t)
(setq flycheck-info t)
(provide 'init-flycheck)
