(require-package 'flycheck)
;;(require-package 'flycheck-highlighting)
;;(require-package 'flycheck-indication)
(require-package 'flycheck-tip)
(global-flycheck-mode)
;;(flymake-cursor-mode t)
(add-hook 'lua-mode-hook 'flymake-lua-load)
;;(add-hook 'find-file-hook 'flymake-find-file-hook)
(provide 'init-flycheck)
